from random import shuffle

x = [
    "for",
    "print(res)",
    "print",
    "def",
    "break",
    "continue",
    "pass",
    "arr[i]",
    "len(arr)",
    "len(s)",
    "#include <iostream>",
    "#include <vector>",
    "#include <set>",
    "using namespace std;",
    "for (int i = 0 ; i < arr.size() ; i++)",
    "vector<int> arr = {}",
    "vector<vector<int>> arr = {}",
    "arr[r][c]",
    "matrix[r][c]",
    "dfs",
    "import",
    "newArr",
    "x",
    "{}",
    "():",
    "for i in range():",
    "while",
    "if",
    "elif",
    "else:",
    "pop",
    "append",
    "row",
    "col",
    "mp = set()",
    "visited = set()",
    "return",
    "[i]",
    "for i in range(len(nums)):",
    "range",
    "left",
    "right",
    "top",
    "bot",
    "import math",
    "import sys",
    "in",
    "set()",
    "add",
    "remove",
    "csum",
    "copy",
    "search",
    "mp = {}",
    "hset = {}",
    "target",
    "rem",
    "arr[r][c]",
    "arr[i]",
    "self.left",
    "self.right",
    "k",
    "int",
    "bool",
    "vector",
    "vector<int>",
]

# randomize coding strings'


shuffle(x)
print(" ".join(x))
shuffle(x)
print(" ".join(x))
